# AUTO-GENERATED by akumi/codegen. Do not edit by hand.
from __future__ import annotations

from typing import Any

from .._transport import SyncTransport


class AgentsResource:
    def __init__(self, transport: SyncTransport) -> None:
        self._transport = transport

    def v1AgentsIndex(self) -> dict[str, Any]:
        return self._transport.request("GET", "/agents", None, None)

    def v1AgentsStore(self, params: dict[str, Any] | None = None) -> dict[str, Any]:
        return self._transport.request("POST", "/agents", None, params)

    def v1AgentsRunsShow(self, run: str) -> dict[str, Any]:
        return self._transport.request("GET", f"/agents/runs/{run}", None, None)

    def v1AgentsShow(self, agent: str) -> dict[str, Any]:
        return self._transport.request("GET", f"/agents/{agent}", None, None)

    def v1AgentsUpdate(
        self, agent: str, params: dict[str, Any] | None = None
    ) -> dict[str, Any]:
        return self._transport.request("PATCH", f"/agents/{agent}", None, params)

    def v1AgentsCopy(
        self, agent: str, params: dict[str, Any] | None = None
    ) -> dict[str, Any]:
        return self._transport.request("POST", f"/agents/{agent}/copy", None, params)

    def v1AgentsVersionsIndex(self, agent: str) -> dict[str, Any]:
        return self._transport.request("GET", f"/agents/{agent}/versions", None, None)

    def v1AgentsVersionsStore(
        self, agent: str, params: dict[str, Any] | None = None
    ) -> dict[str, Any]:
        return self._transport.request(
            "POST", f"/agents/{agent}/versions", None, params
        )

    def v1AgentsVersionsShow(self, agent: str, version: str) -> dict[str, Any]:
        return self._transport.request(
            "GET", f"/agents/{agent}/versions/{version}", None, None
        )

    def v1AgentsRunsStore(
        self, agent: str, params: dict[str, Any] | None = None
    ) -> dict[str, Any]:
        return self._transport.request("POST", f"/agents/{agent}/runs", None, params)
