# AUTO-GENERATED by akumi/codegen. Do not edit by hand.
from __future__ import annotations

from typing import Any

from .._transport import AsyncTransport


class AsyncAgentsResource:
    def __init__(self, transport: AsyncTransport) -> None:
        self._transport = transport

    async def v1AgentsIndex(self) -> dict[str, Any]:
        return await self._transport.arequest("GET", "/agents", None, None)

    async def v1AgentsStore(
        self, params: dict[str, Any] | None = None
    ) -> dict[str, Any]:
        return await self._transport.arequest("POST", "/agents", None, params)

    async def v1AgentsRunsShow(self, run: str) -> dict[str, Any]:
        return await self._transport.arequest("GET", f"/agents/runs/{run}", None, None)

    async def v1AgentsShow(self, agent: str) -> dict[str, Any]:
        return await self._transport.arequest("GET", f"/agents/{agent}", None, None)

    async def v1AgentsUpdate(
        self, agent: str, params: dict[str, Any] | None = None
    ) -> dict[str, Any]:
        return await self._transport.arequest("PATCH", f"/agents/{agent}", None, params)

    async def v1AgentsVersionsIndex(self, agent: str) -> dict[str, Any]:
        return await self._transport.arequest(
            "GET", f"/agents/{agent}/versions", None, None
        )

    async def v1AgentsVersionsStore(
        self, agent: str, params: dict[str, Any] | None = None
    ) -> dict[str, Any]:
        return await self._transport.arequest(
            "POST", f"/agents/{agent}/versions", None, params
        )

    async def v1AgentsVersionsShow(self, agent: str, version: str) -> dict[str, Any]:
        return await self._transport.arequest(
            "GET", f"/agents/{agent}/versions/{version}", None, None
        )

    async def v1AgentsRunsStore(
        self, agent: str, params: dict[str, Any] | None = None
    ) -> dict[str, Any]:
        return await self._transport.arequest(
            "POST", f"/agents/{agent}/runs", None, params
        )
