# AUTO-GENERATED by akumi/codegen. Do not edit by hand.
from __future__ import annotations

from typing import Any

from .._transport import SyncTransport


class AuditLogsResource:
    def __init__(self, transport: SyncTransport) -> None:
        self._transport = transport

    def list(self, query: dict[str, Any] | None = None) -> dict[str, Any]:
        return self._transport.request("GET", "/audit-logs", query, None)

    def get(self, uuid: str) -> dict[str, Any]:
        return self._transport.request("GET", f"/audit-logs/{uuid}", None, None)
