# AUTO-GENERATED by akumi/codegen. Do not edit by hand.
from __future__ import annotations

from typing import Any

from .._transport import AsyncTransport


class AsyncAuditLogsResource:
    def __init__(self, transport: AsyncTransport) -> None:
        self._transport = transport

    async def list(self, query: dict[str, Any] | None = None) -> dict[str, Any]:
        return await self._transport.arequest("GET", "/audit-logs", query, None)

    async def get(self, uuid: str) -> dict[str, Any]:
        return await self._transport.arequest("GET", f"/audit-logs/{uuid}", None, None)
