# AUTO-GENERATED by akumi/codegen. Do not edit by hand.
from __future__ import annotations

from collections.abc import AsyncIterator
from typing import Any

from .._transport import AsyncTransport


class AsyncChatResource:
    def __init__(self, transport: AsyncTransport) -> None:
        self._transport = transport

    async def create(self, params: dict[str, Any] | None = None) -> dict[str, Any]:
        return await self._transport.arequest("POST", "/chat/completions", None, params)

    async def create_streamed(
        self, params: dict[str, Any] | None = None
    ) -> AsyncIterator[dict[str, Any]]:
        async for event in self._transport.astream("POST", "/chat/completions", params):
            yield event
