# AUTO-GENERATED by akumi/codegen. Do not edit by hand.
from __future__ import annotations

from collections.abc import Iterator
from typing import Any

from .._transport import SyncTransport


class ChatResource:
    def __init__(self, transport: SyncTransport) -> None:
        self._transport = transport

    def create(self, params: dict[str, Any] | None = None) -> dict[str, Any]:
        return self._transport.request("POST", "/chat/completions", None, params)

    def create_streamed(
        self, params: dict[str, Any] | None = None
    ) -> Iterator[dict[str, Any]]:
        yield from self._transport.stream("POST", "/chat/completions", params)
