# AUTO-GENERATED by akumi/codegen. Do not edit by hand.
from __future__ import annotations

from typing import Any

from .._transport import SyncTransport


class EmbeddingsResource:
    def __init__(self, transport: SyncTransport) -> None:
        self._transport = transport

    def create(self, params: dict[str, Any] | None = None) -> dict[str, Any]:
        return self._transport.request("POST", "/embeddings", None, params)
