# AUTO-GENERATED by akumi/codegen. Do not edit by hand.
from __future__ import annotations

from typing import Any

from .._transport import AsyncTransport


class AsyncEmbeddingsResource:
    def __init__(self, transport: AsyncTransport) -> None:
        self._transport = transport

    async def create(self, params: dict[str, Any] | None = None) -> dict[str, Any]:
        return await self._transport.arequest("POST", "/embeddings", None, params)
