# AUTO-GENERATED by akumi/codegen. Do not edit by hand.
from __future__ import annotations

from typing import Any

from .._transport import SyncTransport


class MemoryResource:
    def __init__(self, transport: SyncTransport) -> None:
        self._transport = transport

    def forget(self) -> dict[str, Any]:
        return self._transport.request("DELETE", "/memory", None, None)
