# AUTO-GENERATED by akumi/codegen. Do not edit by hand.
from __future__ import annotations

from typing import Any

from .._transport import SyncTransport


class MemoryThreadsResource:
    def __init__(self, transport: SyncTransport) -> None:
        self._transport = transport

    def list(self) -> dict[str, Any]:
        return self._transport.request("GET", "/memory/threads", None, None)

    def create(self) -> dict[str, Any]:
        return self._transport.request("POST", "/memory/threads", None, None)

    def get(self, thread: str) -> dict[str, Any]:
        return self._transport.request("GET", f"/memory/threads/{thread}", None, None)

    def delete(self, thread: str) -> dict[str, Any]:
        return self._transport.request("DELETE", f"/memory/threads/{thread}", None, None)
