# AUTO-GENERATED by akumi/codegen. Do not edit by hand.
from __future__ import annotations

from typing import Any

from .._transport import AsyncTransport


class AsyncMemoryResource:
    def __init__(self, transport: AsyncTransport) -> None:
        self._transport = transport

    async def listThreads(self, query: dict[str, Any] | None = None) -> dict[str, Any]:
        return await self._transport.arequest("GET", "/memory/threads", query, None)

    async def createThread(self) -> dict[str, Any]:
        return await self._transport.arequest("POST", "/memory/threads", None, None)

    async def getThread(self, thread: str) -> dict[str, Any]:
        return await self._transport.arequest(
            "GET", f"/memory/threads/{thread}", None, None
        )

    async def deleteThread(self, thread: str) -> dict[str, Any]:
        return await self._transport.arequest(
            "DELETE", f"/memory/threads/{thread}", None, None
        )

    async def search(self, params: dict[str, Any] | None = None) -> dict[str, Any]:
        return await self._transport.arequest("POST", "/memory/search", None, params)

    async def listFacts(self, query: dict[str, Any] | None = None) -> dict[str, Any]:
        return await self._transport.arequest("GET", "/memory/facts", query, None)

    async def rememberFact(
        self, params: dict[str, Any] | None = None
    ) -> dict[str, Any]:
        return await self._transport.arequest("POST", "/memory/facts", None, params)

    async def forgetFact(self, id: str) -> dict[str, Any]:
        return await self._transport.arequest(
            "DELETE", f"/memory/facts/{id}", None, None
        )

    async def export(self, query: dict[str, Any] | None = None) -> dict[str, Any]:
        return await self._transport.arequest("GET", "/memory/export", query, None)

    async def erase(self) -> dict[str, Any]:
        return await self._transport.arequest("DELETE", "/memory", None, None)

    async def listDocuments(
        self, query: dict[str, Any] | None = None
    ) -> dict[str, Any]:
        return await self._transport.arequest("GET", "/memory/documents", query, None)

    async def ingestDocument(
        self, params: dict[str, Any] | None = None
    ) -> dict[str, Any]:
        return await self._transport.arequest("POST", "/memory/documents", None, params)

    async def getDocument(self, document: str) -> dict[str, Any]:
        return await self._transport.arequest(
            "GET", f"/memory/documents/{document}", None, None
        )

    async def deleteDocument(self, document: str) -> dict[str, Any]:
        return await self._transport.arequest(
            "DELETE", f"/memory/documents/{document}", None, None
        )

    async def listCollections(
        self, query: dict[str, Any] | None = None
    ) -> dict[str, Any]:
        return await self._transport.arequest("GET", "/memory/collections", query, None)

    async def createCollection(
        self, params: dict[str, Any] | None = None
    ) -> dict[str, Any]:
        return await self._transport.arequest(
            "POST", "/memory/collections", None, params
        )

    async def getCollection(self, slug: str) -> dict[str, Any]:
        return await self._transport.arequest(
            "GET", f"/memory/collections/{slug}", None, None
        )

    async def deleteCollection(self, slug: str) -> dict[str, Any]:
        return await self._transport.arequest(
            "DELETE", f"/memory/collections/{slug}", None, None
        )

    async def updateCollection(
        self, slug: str, params: dict[str, Any] | None = None
    ) -> dict[str, Any]:
        return await self._transport.arequest(
            "PATCH", f"/memory/collections/{slug}", None, params
        )
