# AUTO-GENERATED by akumi/codegen. Do not edit by hand.
from __future__ import annotations

from typing import Any

from .._transport import AsyncTransport


class AsyncMemoryThreadsResource:
    def __init__(self, transport: AsyncTransport) -> None:
        self._transport = transport

    async def list(self) -> dict[str, Any]:
        return await self._transport.arequest("GET", "/memory/threads", None, None)

    async def create(self) -> dict[str, Any]:
        return await self._transport.arequest("POST", "/memory/threads", None, None)

    async def get(self, thread: str) -> dict[str, Any]:
        return await self._transport.arequest("GET", f"/memory/threads/{thread}", None, None)

    async def delete(self, thread: str) -> dict[str, Any]:
        return await self._transport.arequest("DELETE", f"/memory/threads/{thread}", None, None)
