# AUTO-GENERATED by akumi/codegen. Do not edit by hand.
from __future__ import annotations

from typing import Any

from .._transport import SyncTransport


class RecallResource:
    def __init__(self, transport: SyncTransport) -> None:
        self._transport = transport

    def listThreads(self, query: dict[str, Any] | None = None) -> dict[str, Any]:
        return self._transport.request("GET", "/recall/threads", query, None)

    def createThread(self) -> dict[str, Any]:
        return self._transport.request("POST", "/recall/threads", None, None)

    def getThread(self, thread: str) -> dict[str, Any]:
        return self._transport.request("GET", f"/recall/threads/{thread}", None, None)

    def deleteThread(self, thread: str) -> dict[str, Any]:
        return self._transport.request(
            "DELETE", f"/recall/threads/{thread}", None, None
        )

    def search(self, params: dict[str, Any] | None = None) -> dict[str, Any]:
        return self._transport.request("POST", "/recall/search", None, params)

    def searchFacts(self, params: dict[str, Any] | None = None) -> dict[str, Any]:
        return self._transport.request("POST", "/recall/facts/search", None, params)

    def listFacts(self, query: dict[str, Any] | None = None) -> dict[str, Any]:
        return self._transport.request("GET", "/recall/facts", query, None)

    def rememberFact(self, params: dict[str, Any] | None = None) -> dict[str, Any]:
        return self._transport.request("POST", "/recall/facts", None, params)

    def forgetFact(self, id: str) -> dict[str, Any]:
        return self._transport.request("DELETE", f"/recall/facts/{id}", None, None)

    def export(self, query: dict[str, Any] | None = None) -> dict[str, Any]:
        return self._transport.request("GET", "/recall/export", query, None)

    def erase(self) -> dict[str, Any]:
        return self._transport.request("DELETE", "/recall", None, None)

    def searchDocuments(self, params: dict[str, Any] | None = None) -> dict[str, Any]:
        return self._transport.request("POST", "/recall/documents/search", None, params)

    def listDocuments(self, query: dict[str, Any] | None = None) -> dict[str, Any]:
        return self._transport.request("GET", "/recall/documents", query, None)

    def ingestDocument(self, params: dict[str, Any] | None = None) -> dict[str, Any]:
        return self._transport.request("POST", "/recall/documents", None, params)

    def getDocument(self, document: str) -> dict[str, Any]:
        return self._transport.request(
            "GET", f"/recall/documents/{document}", None, None
        )

    def deleteDocument(self, document: str) -> dict[str, Any]:
        return self._transport.request(
            "DELETE", f"/recall/documents/{document}", None, None
        )

    def listCollections(self, query: dict[str, Any] | None = None) -> dict[str, Any]:
        return self._transport.request("GET", "/recall/collections", query, None)

    def createCollection(self, params: dict[str, Any] | None = None) -> dict[str, Any]:
        return self._transport.request("POST", "/recall/collections", None, params)

    def getCollection(self, slug: str) -> dict[str, Any]:
        return self._transport.request("GET", f"/recall/collections/{slug}", None, None)

    def deleteCollection(self, slug: str) -> dict[str, Any]:
        return self._transport.request(
            "DELETE", f"/recall/collections/{slug}", None, None
        )

    def updateCollection(
        self, slug: str, params: dict[str, Any] | None = None
    ) -> dict[str, Any]:
        return self._transport.request(
            "PATCH", f"/recall/collections/{slug}", None, params
        )
