# AUTO-GENERATED by akumi/codegen. Do not edit by hand.
from __future__ import annotations

from ._config import ClientConfig
from ._transport import AsyncTransport
from .resources.auditLog_async import AsyncAuditLogResource
from .resources.chatCompletions_async import AsyncChatCompletionsResource
from .resources.embeddings_async import AsyncEmbeddingsResource
from .resources.memory_async import AsyncMemoryResource
from .resources.models_async import AsyncModelsResource
from .resources.scores_async import AsyncScoresResource


class AsyncAkumi:
    def __init__(
        self,
        *,
        api_key: str,
        base_url: str = "https://api.akumi.eu/v1",
        max_retries: int = 2,
    ) -> None:
        config = ClientConfig(
            api_key=api_key, base_url=base_url, max_retries=max_retries
        )
        self._transport = AsyncTransport(config)
        self.auditLog = AsyncAuditLogResource(self._transport)
        self.chatCompletions = AsyncChatCompletionsResource(self._transport)
        self.embeddings = AsyncEmbeddingsResource(self._transport)
        self.memory = AsyncMemoryResource(self._transport)
        self.models = AsyncModelsResource(self._transport)
        self.scores = AsyncScoresResource(self._transport)

    @classmethod
    def from_api_key(cls, api_key: str) -> AsyncAkumi:
        return cls(api_key=api_key)
