# AUTO-GENERATED by akumi/codegen. Do not edit by hand.
from __future__ import annotations

from ._config import ClientConfig
from ._transport import AsyncTransport
from .resources.auditLogs_async import AsyncAuditLogsResource
from .resources.chat_async import AsyncChatResource
from .resources.embeddings_async import AsyncEmbeddingsResource
from .resources.models_async import AsyncModelsResource
from .resources.recall_async import AsyncRecallResource


class AsyncAkumi:
    def __init__(
        self,
        *,
        api_key: str,
        base_url: str = "https://api.akumi.cloud/v1",
        max_retries: int = 2,
    ) -> None:
        config = ClientConfig(
            api_key=api_key, base_url=base_url, max_retries=max_retries
        )
        self._transport = AsyncTransport(config)
        self.recall = AsyncRecallResource(self._transport)
        self.auditLogs = AsyncAuditLogsResource(self._transport)
        self.chat = AsyncChatResource(self._transport)
        self.embeddings = AsyncEmbeddingsResource(self._transport)
        self.models = AsyncModelsResource(self._transport)

    @classmethod
    def from_api_key(cls, api_key: str) -> AsyncAkumi:
        return cls(api_key=api_key)
