# AUTO-GENERATED by akumi/codegen. Do not edit by hand.
from __future__ import annotations

from ._config import ClientConfig
from ._transport import SyncTransport
from .resources.auditLogs_sync import AuditLogsResource
from .resources.chat_sync import ChatResource
from .resources.embeddings_sync import EmbeddingsResource
from .resources.models_sync import ModelsResource
from .resources.memory_sync import MemoryResource
from .resources.memoryThreads_sync import MemoryThreadsResource


class Akumi:
    def __init__(
        self,
        *,
        api_key: str,
        base_url: str = "https://api.akumi.cloud/v1",
        max_retries: int = 2,
    ) -> None:
        config = ClientConfig(api_key=api_key, base_url=base_url, max_retries=max_retries)
        self._transport = SyncTransport(config)
        self.auditLogs = AuditLogsResource(self._transport)
        self.chat = ChatResource(self._transport)
        self.embeddings = EmbeddingsResource(self._transport)
        self.models = ModelsResource(self._transport)
        self.memory = MemoryResource(self._transport)
        self.memoryThreads = MemoryThreadsResource(self._transport)

    @classmethod
    def from_api_key(cls, api_key: str) -> "Akumi":
        return cls(api_key=api_key)
