# AUTO-GENERATED by akumi/codegen. Do not edit by hand.
from __future__ import annotations

from dataclasses import dataclass
from typing import Any


@dataclass
class AuditLogApiResource:
    id: str
    component: str
    action: str
    actorId: int | None
    ipAddress: str | None
    userAgent: str | None
    target: Any | None
    metadata: list[Any] | None
    createdAt: str

    @classmethod
    def from_dict(cls, data: dict[str, Any]) -> AuditLogApiResource:
        return cls(
            id=data["id"],
            component=data["component"],
            action=data["action"],
            actorId=data["actorId"],
            ipAddress=data["ipAddress"],
            userAgent=data["userAgent"],
            target=data["target"],
            metadata=data["metadata"],
            createdAt=data["createdAt"],
        )


@dataclass
class ChatCompletionsRequest:
    model: str
    messages: list[Any]
    temperature: float | None = None
    max_tokens: int | None = None
    stream: bool | None = None
    firewall: bool | None = None
    rag: str | None = None
    user: str | None = None
    thread: str | None = None
    top_p: float | None = None
    presence_penalty: float | None = None
    frequency_penalty: float | None = None
    n: int | None = None
    seed: int | None = None
    logprobs: bool | None = None
    top_logprobs: int | None = None
    max_completion_tokens: int | None = None
    tool_choice: str | None = None
    parallel_tool_calls: bool | None = None
    cache: bool | None = None
    stop: list[str] | None = None
    logit_bias: list[float] | None = None
    response_format: Any | None = None
    tools: list[Any] | None = None

    @classmethod
    def from_dict(cls, data: dict[str, Any]) -> ChatCompletionsRequest:
        return cls(
            model=data["model"],
            messages=data["messages"],
            temperature=data.get("temperature"),
            max_tokens=data.get("max_tokens"),
            stream=data.get("stream"),
            firewall=data.get("firewall"),
            rag=data.get("rag"),
            user=data.get("user"),
            thread=data.get("thread"),
            top_p=data.get("top_p"),
            presence_penalty=data.get("presence_penalty"),
            frequency_penalty=data.get("frequency_penalty"),
            n=data.get("n"),
            seed=data.get("seed"),
            logprobs=data.get("logprobs"),
            top_logprobs=data.get("top_logprobs"),
            max_completion_tokens=data.get("max_completion_tokens"),
            tool_choice=data.get("tool_choice"),
            parallel_tool_calls=data.get("parallel_tool_calls"),
            cache=data.get("cache"),
            stop=data.get("stop"),
            logit_bias=data.get("logit_bias"),
            response_format=data.get("response_format"),
            tools=data.get("tools"),
        )


@dataclass
class EmbeddingsRequest:
    model: str
    input: list[str]
    encoding_format: str | None = None
    dimensions: int | None = None
    user: str | None = None

    @classmethod
    def from_dict(cls, data: dict[str, Any]) -> EmbeddingsRequest:
        return cls(
            model=data["model"],
            input=data["input"],
            encoding_format=data.get("encoding_format"),
            dimensions=data.get("dimensions"),
            user=data.get("user"),
        )


@dataclass
class IngestDocumentRequest:
    title: str
    text: str
    source: str | None = None
    collection: str | None = None

    @classmethod
    def from_dict(cls, data: dict[str, Any]) -> IngestDocumentRequest:
        return cls(
            title=data["title"],
            text=data["text"],
            source=data.get("source"),
            collection=data.get("collection"),
        )


@dataclass
class RememberFactRequest:
    content: str
    user_ref: str

    @classmethod
    def from_dict(cls, data: dict[str, Any]) -> RememberFactRequest:
        return cls(
            content=data["content"],
            user_ref=data["user_ref"],
        )


@dataclass
class SearchDocumentsRequest:
    query: str
    collection: str
    user_ref: str | None = None
    limit: int | None = None

    @classmethod
    def from_dict(cls, data: dict[str, Any]) -> SearchDocumentsRequest:
        return cls(
            query=data["query"],
            collection=data["collection"],
            user_ref=data.get("user_ref"),
            limit=data.get("limit"),
        )


@dataclass
class SearchFactsRequest:
    query: str
    user_ref: str | None = None
    limit: int | None = None

    @classmethod
    def from_dict(cls, data: dict[str, Any]) -> SearchFactsRequest:
        return cls(
            query=data["query"],
            user_ref=data.get("user_ref"),
            limit=data.get("limit"),
        )


@dataclass
class SearchRequest:
    query: str
    user_ref: str | None = None
    limit: int | None = None

    @classmethod
    def from_dict(cls, data: dict[str, Any]) -> SearchRequest:
        return cls(
            query=data["query"],
            user_ref=data.get("user_ref"),
            limit=data.get("limit"),
        )


@dataclass
class StoreCollectionRequest:
    name: str

    @classmethod
    def from_dict(cls, data: dict[str, Any]) -> StoreCollectionRequest:
        return cls(
            name=data["name"],
        )


@dataclass
class ThreadMessageViewModel:
    @classmethod
    def from_dict(cls, data: dict[str, Any]) -> ThreadMessageViewModel:
        return cls()


@dataclass
class ThreadViewModel:
    @classmethod
    def from_dict(cls, data: dict[str, Any]) -> ThreadViewModel:
        return cls()
